# Generated by Django 5.1.3 on 2024-11-16 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_accounthistory_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='DepositHistory',
            fields=[
                ('deposit_id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='api.user')),
                ('user_currency_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deposits', to='api.usercurrencyaccount')),
            ],
        ),
    ]
