# Generated by Django 5.1.3 on 2024-11-19 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_deposithistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accounthistory',
            name='action',
            field=models.CharField(choices=[('income', 'Income'), ('expense', 'Expense')], max_length=8),
        ),
    ]
