# Generated by Django 5.1.3 on 2024-11-19 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_accounthistory_action'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercurrencyaccount',
            name='currency_code',
            field=models.CharField(choices=[('USD', 'US Dollar'), ('EUR', 'Euro'), ('JPY', 'Japanese Yen'), ('GBP', 'British Pound'), ('AUD', 'Australian Dollar'), ('CAD', 'Canadian Dollar'), ('CHF', 'Swiss Franc'), ('SEK', 'Swedish Krona'), ('PLN', 'Polish Zloty')], max_length=3),
        ),
    ]
